version: '3'

volumes: 
  db-data:

services: 
  web:
    build: .
    ports: 
      - '3000:3000'
    volumes:
      - '.:/michigan-kuchikomi'
    environment: 
      - 'DATABASE_PASSWORD=password'
    tty: true
    stdin_open: true
    depends_on: 
      - db
    links: 
      - db
  
  db:
    image: mysql@sha256:43bf7db32d11e75d8463a8bc077f09af5fb5b84b182b1d74124ddca633093bfa
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - 'db-data:/var/lib/mysql'
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306